### PR TITLE
I don't think there will be anymore crypto miners.

### PR DESCRIPTION
**Pull request by alfiephillips**
This is a list of pretty much every single crypto miner on the internet.

### CODE REVIEW

**Comment by Phineas** [comment]
A lot of these domains don't seem to exist, e.g:

```
phin@gateway-j0o43:~$ whois zbwzxxysgs.bid
No Data Found
```

Maybe we can get a script in this repo to filter through the list and remove invalids using GH actions.

**Comment by alfiephillips** [comment]
We could make a shell script and use curl to authenticate the status code of a request?

**Comment by Looskie** [comment]
I loveee toying around with GH Actions, mind if I can give it a shot and make a PR if im successful with it @Phineas ?

**Comment by Phineas** [comment]
> I loveee toying around with GH Actions, mind if I can give it a shot and make a PR if im successful with it @Phineas ?

Sure!!

**Comment by alfiephillips** [comment]
> > I loveee toying around with GH Actions, mind if I can give it a shot and make a PR if im successful with it @Phineas ?
> 
> 
> 
> Sure!!

Can this PR go through since the lists will be filtered with his github actions script? @Phineas

**Comment by Phineas** [comment]
> > > I loveee toying around with GH Actions, mind if I can give it a shot and make a PR if im successful with it @Phineas ?
> > 
> > 
> > Sure!!
> 
> Can this PR go through since the lists will be filtered with his github actions script? @Phineas

Yep 🙂

**Comment by alfiephillips** [comment]
@Phineas I have created a script that removes the inactive files from blocked_domains. I have more to do, I was just asking if your ok with what I'm doing.

**Pull request closed without merging**
