### PR TITLE
crypto mining site

### PR DESCRIPTION
**Pull request by Looskie**
i hope this works? im not sure since its an actual ip instead of a domain

### CODE REVIEW

**Comment by Phineas** [comment]
It won't, this is for domains only. What is the IP address for?

**Comment by Looskie** [comment]
> It won't, this is for domains only. What is the IP address for?

it was a crypto mining site, but it wasnt coming from a domain.

**Comment by Phineas** [comment]
> > It won't, this is for domains only. What is the IP address for?
> 
> 
> 
> it was a crypto mining site, but it wasnt coming from a domain.

Ah okay, we might have to add an IP blacklist file if this practice continues

**Comment by Looskie** [comment]
> > > It won't, this is for domains only. What is the IP address for?
> > 
> > 
> > it was a crypto mining site, but it wasnt coming from a domain.
> 
> Ah okay, we might have to add an IP blacklist file if this practice continues

Sounds good! i'll close this PR for the sake of cleaning up the repo

**Pull request closed without merging**
